name: gluestack_ui
description: "A universal UI library that provides optionally styled and accessible widgets, designed for easy integration into applications developed with Flutter."

homepage: https://flutter.gluestack.io/
repository: https://github.com/gluestack/gluestack-ui-flutter
issue_tracker: https://github.com/gluestack/gluestack-ui-flutter/issues
documentation: https://flutter.gluestack.io/

version: 0.1.0-beta.2

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fluttertoast: ^8.2.4
  url_launcher: ^6.2.1
  get_it: ^7.6.4
  google_fonts: <=6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Sono
      fonts:
        - asset: assets/fonts/Sono-VariableFont.ttf

# TODO: Add relevent icon or screenshot to show in pub.dev listing.
screenshots:

# Add upto 5 topics to get indexed better on pub.dev
topics:
  - ui
  - widgets
  - design-system
  - ui-library
